#!/usr/bin/env python3

import sys, os

ARG = sys.argv[:1]

# https://stackoverflow.com/questions/4842424/list-of-ansi-color-escape-sequences
class bcolors:
    HEADER = '\033[95m'
    OKBLUE = '\033[94m'
    OKGREEN = '\033[92m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    ENDC = '\033[0m'

    def disable(self):
        self.HEADER = ''
        self.OKBLUE = ''
        self.OKGREEN = ''
        self.WARNING = ''
        self.FAIL = ''
        self.ENDC = ''

def help():
	text = """ asdfasdf
	asdfasdf
	asdfasdfasdf
	asdfasdfasdfasdf
	asdasdf
	asdfasdf
		"""

	print(f"{bcolors.OKGREEN}{text}{bcolors.ENDC}")

def main():
	help()
	
if __name__ == "__main__":
	main()

